### ISSUE TITLE
NrqlConditionDSL does not support signal loss configuration.

### ISSUE THREAD

**Issue by piotrwroblewski90** [ocadotechnology/newrelic-alerts-configurator#38]
Hi,
We use **newrelic-alerts-configurator-dsl** in our project and unfortunately the DSL does not support new rules for signal loss. Would it be possible to add such option to NrqlConditionDsl?
Best regards,
Piotr W.

**Comment by pcimcioch** [comment]
Hi! Yes, we'll take a look at it

**Comment by pcimcioch** [comment]
We added it. Version 3.5.2 released, it should be available in central maven in few hours

**Comment by piotrwroblewski90** [comment]
Thank you! It works great.
